# Default values for Thunder
# This is a YAML-formatted file.


deployment:
  replicaCount: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  apparmor:
    enabled: false
    profile: "RuntimeDefault"
  securityContext:
    enableRunAsUser: true
    runAsUser: 100
    seccompProfile:
      enabled: true
      type: "RuntimeDefault"
  # Pod termination grace period. K8s API server waits this period after pre stop hook and sending TERM signal
  terminationGracePeriodSeconds: 10
  image:
    # -- Container image registry host name
    registry: "ghcr.io/asgardeo"
    # -- Container image repository name
    repository: "thunder"
    # -- Container image digest
    digest: ""
    # -- Container image tag. Either "tag" or "digest" should be defined
    tag: "0.6.0"
    pullPolicy: "Always"
  startupProbe:
    initialDelaySeconds: 1
    periodSeconds: 2
    failureThreshold: 30
  livenessProbe:
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 1
    periodSeconds: 1
  container:
    port: 8090
  resources:
    limits:
      cpu: 2
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 512Mi

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "thunder-service-account"
  create: true

service:
  port: 8090

ingress:
  className: "nginx"
  commonAnnotations: &commonAnnotations
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/session-cookie-conditional-samesite-none: "true"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: paf
    nginx.ingress.kubernetes.io/session-cookie-path: /
    nginx.ingress.kubernetes.io/session-cookie-samesite: None
  customAnnotations: &customAnnotations
    {}
  combinedAnnotations:
    !!merge <<: *commonAnnotations
    !!merge <<: *customAnnotations
  hostname: thunder.local
  paths:
    - path: /
      pathType: Prefix
  tlsSecretsName: "thunder-tls"

# Thunder specific configurations
configuration:
  # Server configuration
  server:
    hostname: "0.0.0.0"
    port: 8080

  # Gate client configuration
  gateClient:
    hostname: "localhost"
    port: 9090
    scheme: "https"
    loginPath: "/login"
    errorPath: "/error"

  # Security configuration
  security:
    certFile: "repository/resources/security/server.cert"
    keyFile: "repository/resources/security/server.key"

  # Database configuration
  database:
    identity:
      type: "sqlite" # postgres or sqlite
      host: "localhost"
      port: 5432
      name: "thunder"
      username: "thunder"
      password: "thunder"
      path: "repository/database"
      sqlitePath: "repository/database/thunder.db"
      options: "_journal_mode=WAL&_busy_timeout=5000"
      sslmode: "disable"
    # Runtime database configuration
    runtime:
      type: "sqlite" # postgres or sqlite
      host: "localhost"
      port: 5432
      name: "thunder"
      username: "thunder"
      password: "thunder"
      path: "repository/database"
      sqlitePath: "repository/database/thunder.db"
      options: "_journal_mode=WAL&_busy_timeout=5000"
      sslmode: "disable"

  # Cache configuration
  cache:
    disabled: false
    type: "inmemory"
    size: 1000
    ttl: 3600
    evictionPolicy: "LRU"
    cleanupInterval: 300

  # OAuth configuration
  oauth:
    jwt:
      issuer: "thunder"
      validityPeriod: 3600
    refreshToken:
      renewOnGrant: false
      validityPeriod: 86400

  # Flow configuration
  flow:
    graphDirectory: "repository/resources/graphs/"
    authn:
      defaultFlow: "auth_flow_config_basic"

  # CORS configuration
  cors:
    allowedOrigins:
      - "https://localhost:3000"
      - "https://localhost:9001"
      - "https://localhost:9090"
